### ISSUE TITLE
建议构建releases维护依赖库版本

### ISSUE THREAD

**Issue by eryajf** [wenerme/go-wecom#2]
使用release维护go依赖库版本的好处不言而喻，建议项目在适当情况下，通过tag版本进行维护，可以添加Actions自动给项目构建release以及说明，只需要操心发布就OK了

**Comment by wenerme** [comment]
目前这个库还不是很好，库里的内容都是生成的，现在生成逻辑还不在库里，因为写了第一版后微信的文档格式变了，这个重新调整后可以考虑加个版本号。

**Comment by eryajf** [comment]
> 创建了 v0.10.1

可参考这里，配置Actions自动发布，会省心很多：[https://wiki.eryajf.net/pages/f3e878/](https://wiki.eryajf.net/pages/f3e878/)
